export type Coord = { x: number; y: number };

export type StopPoint = {
  key: string;       // "branchId:stopId"
  name: string;
  labelSide: "left" | "right" | "up" | "down";
};

// Coordinate lookup by "branchId:stopId"
export const redLineCoords: Record<string, Coord> = {
  "red-trunk:alewife":           { x: 240, y: 60 },
  "red-trunk:davis":             { x: 240, y: 130 },
  "red-trunk:porter":            { x: 240, y: 200 },
  "red-trunk:harvard":           { x: 240, y: 270 },
  "red-trunk:central":           { x: 240, y: 340 },
  "red-trunk:kendall-mit":       { x: 240, y: 410 },
  "red-trunk:charles-mgh":       { x: 240, y: 480 },
  "red-trunk:park-street":       { x: 240, y: 550 },
  "red-trunk:downtown-crossing": { x: 240, y: 620 },
  "red-trunk:south-station":     { x: 240, y: 690 },
  "red-trunk:broadway":          { x: 240, y: 760 },
  "red-trunk:andrew":            { x: 240, y: 830 },
  "red-trunk:jfk-umass":        { x: 240, y: 900 },
  "red-ashmont:savin-hill":      { x: 160, y: 970 },
  "red-ashmont:fields-corner":   { x: 120, y: 1040 },
  "red-ashmont:shawmut":        { x: 120, y: 1110 },
  "red-ashmont:ashmont":        { x: 120, y: 1180 },
  "red-braintree:north-quincy":  { x: 320, y: 970 },
  "red-braintree:wollaston":     { x: 360, y: 1040 },
  "red-braintree:quincy-center": { x: 360, y: 1110 },
  "red-braintree:quincy-adams":  { x: 360, y: 1180 },
  "red-braintree:braintree":     { x: 360, y: 1250 },
};

// Ordered keys for drawing each rail segment as a polyline
export const redLinePaths: Record<string, string[]> = {
  trunk: [
    "red-trunk:alewife",
    "red-trunk:davis",
    "red-trunk:porter",
    "red-trunk:harvard",
    "red-trunk:central",
    "red-trunk:kendall-mit",
    "red-trunk:charles-mgh",
    "red-trunk:park-street",
    "red-trunk:downtown-crossing",
    "red-trunk:south-station",
    "red-trunk:broadway",
    "red-trunk:andrew",
    "red-trunk:jfk-umass",
  ],
  ashmont: [
    "red-trunk:jfk-umass",
    "red-ashmont:savin-hill",
    "red-ashmont:fields-corner",
    "red-ashmont:shawmut",
    "red-ashmont:ashmont",
  ],
  braintree: [
    "red-trunk:jfk-umass",
    "red-braintree:north-quincy",
    "red-braintree:wollaston",
    "red-braintree:quincy-center",
    "red-braintree:quincy-adams",
    "red-braintree:braintree",
  ],
};

// Orange Line — single branch, straight vertical at x=420, 60px spacing
export const orangeLineCoords: Record<string, Coord> = {
  "orange-main:oak-grove":          { x: 420, y: 60 },
  "orange-main:malden-center":      { x: 420, y: 120 },
  "orange-main:wellington":         { x: 420, y: 180 },
  "orange-main:assembly":           { x: 420, y: 240 },
  "orange-main:sullivan-square":    { x: 420, y: 300 },
  "orange-main:community-college":  { x: 420, y: 360 },
  "orange-main:north-station":      { x: 420, y: 420 },
  "orange-main:haymarket":          { x: 420, y: 480 },
  "orange-main:state":              { x: 420, y: 540 },
  "orange-main:downtown-crossing":  { x: 420, y: 600 },
  "orange-main:chinatown":          { x: 420, y: 660 },
  "orange-main:tufts-medical-center": { x: 420, y: 720 },
  "orange-main:back-bay":           { x: 420, y: 780 },
  "orange-main:massachusetts-ave":  { x: 420, y: 840 },
  "orange-main:ruggles":            { x: 420, y: 900 },
  "orange-main:roxbury-crossing":   { x: 420, y: 960 },
  "orange-main:jackson-square":     { x: 420, y: 1020 },
  "orange-main:stony-brook":        { x: 420, y: 1080 },
  "orange-main:green-street":       { x: 420, y: 1140 },
  "orange-main:forest-hills":       { x: 420, y: 1200 },
};

export const orangeLinePaths: Record<string, string[]> = {
  main: [
    "orange-main:oak-grove",
    "orange-main:malden-center",
    "orange-main:wellington",
    "orange-main:assembly",
    "orange-main:sullivan-square",
    "orange-main:community-college",
    "orange-main:north-station",
    "orange-main:haymarket",
    "orange-main:state",
    "orange-main:downtown-crossing",
    "orange-main:chinatown",
    "orange-main:tufts-medical-center",
    "orange-main:back-bay",
    "orange-main:massachusetts-ave",
    "orange-main:ruggles",
    "orange-main:roxbury-crossing",
    "orange-main:jackson-square",
    "orange-main:stony-brook",
    "orange-main:green-street",
    "orange-main:forest-hills",
  ],
};

export const orangeLineStops: StopPoint[] = [
  { key: "orange-main:oak-grove",           name: "Oak Grove",           labelSide: "right" },
  { key: "orange-main:malden-center",       name: "Malden Center",       labelSide: "right" },
  { key: "orange-main:wellington",          name: "Wellington",          labelSide: "right" },
  { key: "orange-main:assembly",            name: "Assembly",            labelSide: "right" },
  { key: "orange-main:sullivan-square",     name: "Sullivan Square",     labelSide: "right" },
  { key: "orange-main:community-college",   name: "Community College",   labelSide: "right" },
  { key: "orange-main:north-station",       name: "North Station",       labelSide: "right" },
  { key: "orange-main:haymarket",           name: "Haymarket",           labelSide: "right" },
  { key: "orange-main:state",               name: "State",               labelSide: "right" },
  { key: "orange-main:downtown-crossing",   name: "Downtown Crossing",   labelSide: "right" },
  { key: "orange-main:chinatown",           name: "Chinatown",           labelSide: "right" },
  { key: "orange-main:tufts-medical-center",name: "Tufts Medical Center",labelSide: "right" },
  { key: "orange-main:back-bay",            name: "Back Bay",            labelSide: "right" },
  { key: "orange-main:massachusetts-ave",   name: "Massachusetts Ave",   labelSide: "right" },
  { key: "orange-main:ruggles",             name: "Ruggles",             labelSide: "right" },
  { key: "orange-main:roxbury-crossing",    name: "Roxbury Crossing",    labelSide: "right" },
  { key: "orange-main:jackson-square",      name: "Jackson Square",      labelSide: "right" },
  { key: "orange-main:stony-brook",         name: "Stony Brook",         labelSide: "right" },
  { key: "orange-main:green-street",        name: "Green Street",        labelSide: "right" },
  { key: "orange-main:forest-hills",        name: "Forest Hills",        labelSide: "right" },
];

// Blue Line — single branch, horizontal at y=510, 50px spacing west→east
export const blueLineCoords: Record<string, Coord> = {
  "blue-main:bowdoin":          { x: 60,  y: 510 },
  "blue-main:government-center":{ x: 110, y: 510 },
  "blue-main:state":            { x: 160, y: 510 },
  "blue-main:aquarium":         { x: 210, y: 510 },
  "blue-main:maverick":         { x: 260, y: 510 },
  "blue-main:airport":          { x: 310, y: 510 },
  "blue-main:wood-island":      { x: 360, y: 510 },
  "blue-main:orient-heights":   { x: 410, y: 510 },
  "blue-main:suffolk-downs":    { x: 460, y: 510 },
  "blue-main:beachmont":        { x: 510, y: 510 },
  "blue-main:revere-beach":     { x: 560, y: 510 },
  "blue-main:wonderland":       { x: 610, y: 510 },
};

export const blueLinePaths: Record<string, string[]> = {
  main: [
    "blue-main:bowdoin",
    "blue-main:government-center",
    "blue-main:state",
    "blue-main:aquarium",
    "blue-main:maverick",
    "blue-main:airport",
    "blue-main:wood-island",
    "blue-main:orient-heights",
    "blue-main:suffolk-downs",
    "blue-main:beachmont",
    "blue-main:revere-beach",
    "blue-main:wonderland",
  ],
};

export const blueLineStops: StopPoint[] = [
  { key: "blue-main:bowdoin",           name: "Bowdoin",           labelSide: "up" },
  { key: "blue-main:government-center", name: "Government Center", labelSide: "up" },
  { key: "blue-main:state",             name: "State",             labelSide: "up" },
  { key: "blue-main:aquarium",          name: "Aquarium",          labelSide: "up" },
  { key: "blue-main:maverick",          name: "Maverick",          labelSide: "up" },
  { key: "blue-main:airport",           name: "Airport",           labelSide: "up" },
  { key: "blue-main:wood-island",       name: "Wood Island",       labelSide: "up" },
  { key: "blue-main:orient-heights",    name: "Orient Heights",    labelSide: "up" },
  { key: "blue-main:suffolk-downs",     name: "Suffolk Downs",     labelSide: "up" },
  { key: "blue-main:beachmont",         name: "Beachmont",         labelSide: "up" },
  { key: "blue-main:revere-beach",      name: "Revere Beach",      labelSide: "up" },
  { key: "blue-main:wonderland",        name: "Wonderland",        labelSide: "up" },
];

// All unique stops to render (each appears once)
export const redLineStops: StopPoint[] = [
  { key: "red-trunk:alewife",           name: "Alewife",           labelSide: "right" },
  { key: "red-trunk:davis",             name: "Davis",             labelSide: "right" },
  { key: "red-trunk:porter",            name: "Porter",            labelSide: "right" },
  { key: "red-trunk:harvard",           name: "Harvard",           labelSide: "right" },
  { key: "red-trunk:central",           name: "Central",           labelSide: "right" },
  { key: "red-trunk:kendall-mit",       name: "Kendall/MIT",       labelSide: "right" },
  { key: "red-trunk:charles-mgh",       name: "Charles/MGH",       labelSide: "right" },
  { key: "red-trunk:park-street",       name: "Park Street",       labelSide: "right" },
  { key: "red-trunk:downtown-crossing", name: "Downtown Crossing", labelSide: "right" },
  { key: "red-trunk:south-station",     name: "South Station",     labelSide: "right" },
  { key: "red-trunk:broadway",          name: "Broadway",          labelSide: "right" },
  { key: "red-trunk:andrew",            name: "Andrew",            labelSide: "right" },
  { key: "red-trunk:jfk-umass",        name: "JFK/UMass",         labelSide: "right" },
  { key: "red-ashmont:savin-hill",      name: "Savin Hill",        labelSide: "left"  },
  { key: "red-ashmont:fields-corner",   name: "Fields Corner",     labelSide: "left"  },
  { key: "red-ashmont:shawmut",        name: "Shawmut",           labelSide: "left"  },
  { key: "red-ashmont:ashmont",        name: "Ashmont",           labelSide: "left"  },
  { key: "red-braintree:north-quincy",  name: "North Quincy",      labelSide: "right" },
  { key: "red-braintree:wollaston",     name: "Wollaston",         labelSide: "right" },
  { key: "red-braintree:quincy-center", name: "Quincy Center",     labelSide: "right" },
  { key: "red-braintree:quincy-adams",  name: "Quincy Adams",      labelSide: "right" },
  { key: "red-braintree:braintree",     name: "Braintree",         labelSide: "right" },
];

// ─── Green Line ───────────────────────────────────────────────────────────────
// Trunk: horizontal at y=170, x=110 (Kenmore) → x=660 (Lechmere), 55px spacing
// Branches fan left from Kenmore: D at y=110, C at y=260, B at y=400 (40px stops)
// E goes south from Copley at x=165, 50px spacing
export const greenLineCoords: Record<string, Coord> = {
  // Trunk
  "green-trunk:kenmore":                { x: 110, y: 170 },
  "green-trunk:hynes-convention-center":{ x: 165, y: 170 },
  "green-trunk:copley":                 { x: 220, y: 170 },
  "green-trunk:arlington":              { x: 275, y: 170 },
  "green-trunk:boylston":               { x: 330, y: 170 },
  "green-trunk:park-street":            { x: 385, y: 170 },
  "green-trunk:government-center":      { x: 440, y: 170 },
  "green-trunk:haymarket":              { x: 495, y: 170 },
  "green-trunk:north-station":          { x: 550, y: 170 },
  "green-trunk:science-park-west-end":  { x: 605, y: 170 },
  "green-trunk:lechmere":               { x: 660, y: 170 },
  // B branch — y=320, x decreases 40px/stop from x=50
  "green-b:blandford-street":           { x:   50, y: 400 },
  "green-b:boston-university-east":     { x:   10, y: 400 },
  "green-b:boston-university-central":  { x:  -30, y: 400 },
  "green-b:boston-university-west":     { x:  -70, y: 400 },
  "green-b:st-paul-street-b":           { x: -110, y: 400 },
  "green-b:pleasant-street":            { x: -150, y: 400 },
  "green-b:babcock-street":             { x: -190, y: 400 },
  "green-b:packards-corner":            { x: -230, y: 400 },
  "green-b:harvard-ave":                { x: -270, y: 400 },
  "green-b:griggs-street":              { x: -310, y: 400 },
  "green-b:allston-street":             { x: -350, y: 400 },
  "green-b:warren-street":              { x: -390, y: 400 },
  "green-b:washington-street":          { x: -430, y: 400 },
  "green-b:sutherland-road":            { x: -470, y: 400 },
  "green-b:chestnut-hill-ave":          { x: -510, y: 400 },
  "green-b:south-street":               { x: -550, y: 400 },
  "green-b:boston-college":             { x: -590, y: 400 },
  "green-b:east-somerville":            { x: -630, y: 400 },
  "green-b:union-square":               { x: -670, y: 400 },
  // C branch — y=230, x decreases 40px/stop from x=50
  "green-c:saint-mary-s-street":        { x:   50, y: 260 },
  "green-c:hawes-street":               { x:   10, y: 260 },
  "green-c:kent-street":                { x:  -30, y: 260 },
  "green-c:st-paul-street-c":           { x:  -70, y: 260 },
  "green-c:coolidge-corner":            { x: -110, y: 260 },
  "green-c:summit-ave":                 { x: -150, y: 260 },
  "green-c:brandon-hall":               { x: -190, y: 260 },
  "green-c:fairbanks-street":           { x: -230, y: 260 },
  "green-c:washington-square":          { x: -270, y: 260 },
  "green-c:tappan-street":              { x: -310, y: 260 },
  "green-c:dean-road":                  { x: -350, y: 260 },
  "green-c:englewood-ave":              { x: -390, y: 260 },
  "green-c:cleveland-circle":           { x: -430, y: 260 },
  // D branch — y=80, x decreases 40px/stop from x=50
  "green-d:fenway":                     { x:   50, y: 110 },
  "green-d:longwood":                   { x:   10, y: 110 },
  "green-d:brookline-village":          { x:  -30, y: 110 },
  "green-d:brookline-hills":            { x:  -70, y: 110 },
  "green-d:beaconsfield":               { x: -110, y: 110 },
  "green-d:reservoir":                  { x: -150, y: 110 },
  "green-d:chestnut-hill":              { x: -190, y: 110 },
  "green-d:newton-centre":              { x: -230, y: 110 },
  "green-d:newton-highlands":           { x: -270, y: 110 },
  "green-d:eliot":                      { x: -310, y: 110 },
  "green-d:waban":                      { x: -350, y: 110 },
  "green-d:woodland":                   { x: -390, y: 110 },
  "green-d:riverside":                  { x: -430, y: 110 },
  "green-d:east-somerville":            { x: -470, y: 110 },
  "green-d:gilman-square":              { x: -510, y: 110 },
  "green-d:magoun-square":              { x: -550, y: 110 },
  "green-d:ball-square":                { x: -590, y: 110 },
  "green-d:medford-tufts":              { x: -630, y: 110 },
  // E branch — x=285, y increases 50px/stop from y=220
  "green-e:prudential":                 { x: 165, y: 220 },
  "green-e:symphony":                   { x: 165, y: 270 },
  "green-e:northeastern":               { x: 165, y: 400 },
  "green-e:museum-of-fine-arts":        { x: 165, y: 370 },
  "green-e:longwood-medical-area":      { x: 165, y: 420 },
  "green-e:brigham-circle":             { x: 165, y: 470 },
  "green-e:fenwood-road":               { x: 165, y: 520 },
  "green-e:mission-park":               { x: 165, y: 570 },
  "green-e:riverway":                   { x: 165, y: 620 },
  "green-e:back-of-the-hill":           { x: 165, y: 670 },
  "green-e:heath-street":               { x: 165, y: 720 },
};

export const greenLinePaths: Record<string, string[]> = {
  trunk: [
    "green-trunk:kenmore", "green-trunk:hynes-convention-center",
    "green-trunk:copley", "green-trunk:arlington", "green-trunk:boylston",
    "green-trunk:park-street", "green-trunk:government-center",
    "green-trunk:haymarket", "green-trunk:north-station",
    "green-trunk:science-park-west-end", "green-trunk:lechmere",
  ],
  // Branches start from trunk junction so the rail connects visually
  b: [
    "green-trunk:kenmore",
    "green-b:blandford-street", "green-b:boston-university-east",
    "green-b:boston-university-central", "green-b:boston-university-west",
    "green-b:st-paul-street-b", "green-b:pleasant-street",
    "green-b:babcock-street", "green-b:packards-corner",
    "green-b:harvard-ave", "green-b:griggs-street", "green-b:allston-street",
    "green-b:warren-street", "green-b:washington-street",
    "green-b:sutherland-road", "green-b:chestnut-hill-ave",
    "green-b:south-street", "green-b:boston-college",
    "green-b:east-somerville", "green-b:union-square",
  ],
  c: [
    "green-trunk:kenmore",
    "green-c:saint-mary-s-street", "green-c:hawes-street",
    "green-c:kent-street", "green-c:st-paul-street-c",
    "green-c:coolidge-corner", "green-c:summit-ave", "green-c:brandon-hall",
    "green-c:fairbanks-street", "green-c:washington-square",
    "green-c:tappan-street", "green-c:dean-road",
    "green-c:englewood-ave", "green-c:cleveland-circle",
  ],
  d: [
    "green-trunk:kenmore",
    "green-d:fenway", "green-d:longwood", "green-d:brookline-village",
    "green-d:brookline-hills", "green-d:beaconsfield", "green-d:reservoir",
    "green-d:chestnut-hill", "green-d:newton-centre",
    "green-d:newton-highlands", "green-d:eliot", "green-d:waban",
    "green-d:woodland", "green-d:riverside", "green-d:east-somerville",
    "green-d:gilman-square", "green-d:magoun-square",
    "green-d:ball-square", "green-d:medford-tufts",
  ],
  e: [
    "green-trunk:copley",
    "green-e:prudential", "green-e:symphony", "green-e:northeastern",
    "green-e:museum-of-fine-arts", "green-e:longwood-medical-area",
    "green-e:brigham-circle", "green-e:fenwood-road", "green-e:mission-park",
    "green-e:riverway", "green-e:back-of-the-hill", "green-e:heath-street",
  ],
};

export const greenLineStops: StopPoint[] = [
  // Trunk — labels below (away from top edge)
  { key: "green-trunk:kenmore",                 name: "Kenmore",                 labelSide: "down" },
  { key: "green-trunk:hynes-convention-center", name: "Hynes Convention Center", labelSide: "down" },
  { key: "green-trunk:copley",                  name: "Copley",                  labelSide: "down" },
  { key: "green-trunk:arlington",               name: "Arlington",               labelSide: "down" },
  { key: "green-trunk:boylston",                name: "Boylston",                labelSide: "down" },
  { key: "green-trunk:park-street",             name: "Park Street",             labelSide: "down" },
  { key: "green-trunk:government-center",       name: "Government Center",       labelSide: "down" },
  { key: "green-trunk:haymarket",               name: "Haymarket",               labelSide: "down" },
  { key: "green-trunk:north-station",           name: "North Station",           labelSide: "down" },
  { key: "green-trunk:science-park-west-end",   name: "Science Park/West End",   labelSide: "down" },
  { key: "green-trunk:lechmere",                name: "Lechmere",                labelSide: "down" },
  // D branch — labels above (away from trunk)
  { key: "green-d:fenway",          name: "Fenway",           labelSide: "up" },
  { key: "green-d:longwood",        name: "Longwood",         labelSide: "up" },
  { key: "green-d:brookline-village",name:"Brookline Village", labelSide: "up" },
  { key: "green-d:brookline-hills", name: "Brookline Hills",  labelSide: "up" },
  { key: "green-d:beaconsfield",    name: "Beaconsfield",     labelSide: "up" },
  { key: "green-d:reservoir",       name: "Reservoir",        labelSide: "up" },
  { key: "green-d:chestnut-hill",   name: "Chestnut Hill",    labelSide: "up" },
  { key: "green-d:newton-centre",   name: "Newton Centre",    labelSide: "up" },
  { key: "green-d:newton-highlands",name: "Newton Highlands", labelSide: "up" },
  { key: "green-d:eliot",           name: "Eliot",            labelSide: "up" },
  { key: "green-d:waban",           name: "Waban",            labelSide: "up" },
  { key: "green-d:woodland",        name: "Woodland",         labelSide: "up" },
  { key: "green-d:riverside",       name: "Riverside",        labelSide: "up" },
  { key: "green-d:east-somerville", name: "East Somerville",  labelSide: "up" },
  { key: "green-d:gilman-square",   name: "Gilman Square",    labelSide: "up" },
  { key: "green-d:magoun-square",   name: "Magoun Square",    labelSide: "up" },
  { key: "green-d:ball-square",     name: "Ball Square",      labelSide: "up" },
  { key: "green-d:medford-tufts",   name: "Medford/Tufts",    labelSide: "up" },
  // C branch — labels below (toward B, but different x from B stops)
  { key: "green-c:saint-mary-s-street", name: "Saint Mary's Street", labelSide: "down" },
  { key: "green-c:hawes-street",        name: "Hawes Street",        labelSide: "down" },
  { key: "green-c:kent-street",         name: "Kent Street",         labelSide: "down" },
  { key: "green-c:st-paul-street-c",    name: "St. Paul Street",     labelSide: "down" },
  { key: "green-c:coolidge-corner",     name: "Coolidge Corner",     labelSide: "down" },
  { key: "green-c:summit-ave",          name: "Summit Ave",          labelSide: "down" },
  { key: "green-c:brandon-hall",        name: "Brandon Hall",        labelSide: "down" },
  { key: "green-c:fairbanks-street",    name: "Fairbanks Street",    labelSide: "down" },
  { key: "green-c:washington-square",   name: "Washington Square",   labelSide: "down" },
  { key: "green-c:tappan-street",       name: "Tappan Street",       labelSide: "down" },
  { key: "green-c:dean-road",           name: "Dean Road",           labelSide: "down" },
  { key: "green-c:englewood-ave",       name: "Englewood Ave",       labelSide: "down" },
  { key: "green-c:cleveland-circle",    name: "Cleveland Circle",    labelSide: "down" },
  // B branch — labels above (toward C, but each branch occupies different x range)
  { key: "green-b:blandford-street",          name: "Blandford Street",         labelSide: "up" },
  { key: "green-b:boston-university-east",    name: "Boston University East",   labelSide: "up" },
  { key: "green-b:boston-university-central", name: "Boston University Central",labelSide: "up" },
  { key: "green-b:boston-university-west",    name: "Boston University West",   labelSide: "up" },
  { key: "green-b:st-paul-street-b",          name: "St. Paul Street",          labelSide: "up" },
  { key: "green-b:pleasant-street",           name: "Pleasant Street",          labelSide: "up" },
  { key: "green-b:babcock-street",            name: "Babcock Street",           labelSide: "up" },
  { key: "green-b:packards-corner",           name: "Packards Corner",          labelSide: "up" },
  { key: "green-b:harvard-ave",               name: "Harvard Ave",              labelSide: "up" },
  { key: "green-b:griggs-street",             name: "Griggs Street",            labelSide: "up" },
  { key: "green-b:allston-street",            name: "Allston Street",           labelSide: "up" },
  { key: "green-b:warren-street",             name: "Warren Street",            labelSide: "up" },
  { key: "green-b:washington-street",         name: "Washington Street",        labelSide: "up" },
  { key: "green-b:sutherland-road",           name: "Sutherland Road",          labelSide: "up" },
  { key: "green-b:chestnut-hill-ave",         name: "Chestnut Hill Ave",        labelSide: "up" },
  { key: "green-b:south-street",              name: "South Street",             labelSide: "up" },
  { key: "green-b:boston-college",            name: "Boston College",           labelSide: "up" },
  { key: "green-b:east-somerville",           name: "East Somerville",          labelSide: "up" },
  { key: "green-b:union-square",              name: "Union Square",             labelSide: "up" },
  // E branch — labels left (between Red and E line)
  { key: "green-e:prudential",            name: "Prudential",            labelSide: "left" },
  { key: "green-e:symphony",              name: "Symphony",              labelSide: "left" },
  { key: "green-e:northeastern",          name: "Northeastern",          labelSide: "left" },
  { key: "green-e:museum-of-fine-arts",   name: "Museum of Fine Arts",   labelSide: "left" },
  { key: "green-e:longwood-medical-area", name: "Longwood Medical Area", labelSide: "left" },
  { key: "green-e:brigham-circle",        name: "Brigham Circle",        labelSide: "left" },
  { key: "green-e:fenwood-road",          name: "Fenwood Road",          labelSide: "left" },
  { key: "green-e:mission-park",          name: "Mission Park",          labelSide: "left" },
  { key: "green-e:riverway",              name: "Riverway",              labelSide: "left" },
  { key: "green-e:back-of-the-hill",      name: "Back of the Hill",      labelSide: "left" },
  { key: "green-e:heath-street",          name: "Heath Street",          labelSide: "left" },
];
